#!/usr/bin/env node
/**
 * Builds web/public/worker/rare-atlas-worker.mjs: ONE self-contained file (no imports from this repo,
 * no npm dependencies) that volunteers download and run with Node >= 20.
 *
 *   node pipeline/crowd/build_worker.mjs
 *
 * It inlines integrations/openai/siwc.mjs (Sign in with ChatGPT loopback login, token storage and refresh)
 * and integrations/openai/llm.mjs (Responses API streaming, structured outputs, error mapping) and appends
 * pipeline/crowd/worker_main.mjs (the claim -> extract -> submit loop). Re-run after changing any of them.
 *
 * Changes made while inlining (everything else is copied verbatim):
 *  - imports are replaced by one combined node:* import header; `export` keywords are dropped;
 *  - credentials live in ~/.rare-atlas-worker/secrets/ (RARE_ATLAS_HOME / RARE_ATLAS_SECRETS_DIR override),
 *    not in the repo's .secrets/;
 *  - llm.mjs no longer reads a .env.local file; its duplicate isObject/CLI helpers are dropped;
 *  - CLI hints say "node rare-atlas-worker.mjs" instead of "node integrations/openai/cli.mjs".
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = path.join(ROOT, 'web', 'public', 'worker', 'rare-atlas-worker.mjs');

const stripImports = (s) => s.replace(/^import[\s\S]*?from\s+['"][^'"]+['"];\s*\n/gm, '');
const stripExports = (s) => s.replace(/^export (?=(async )?(function|const|class|let) )/gm, '');
function mustReplace(s, from, to, what) {
  if (!s.includes(from)) throw new Error(`build_worker: expected text not found (${what}); update build_worker.mjs`);
  return s.replace(from, to);
}

let siwc = readFileSync(path.join(ROOT, 'integrations', 'openai', 'siwc.mjs'), 'utf8');
let llm = readFileSync(path.join(ROOT, 'integrations', 'openai', 'llm.mjs'), 'utf8');
const main = readFileSync(path.join(ROOT, 'pipeline', 'crowd', 'worker_main.mjs'), 'utf8');

siwc = stripExports(stripImports(siwc));
siwc = mustReplace(
  siwc,
  "const HERE = path.dirname(fileURLToPath(import.meta.url));\nconst PROJECT_ROOT = path.resolve(process.env.SIWC_PROJECT_ROOT || path.join(HERE, '..', '..'));\nconst SECRETS_DIR = path.join(PROJECT_ROOT, '.secrets');",
  "const PROJECT_ROOT = WORKER_HOME;\nconst SECRETS_DIR = process.env.RARE_ATLAS_SECRETS_DIR ? path.resolve(process.env.RARE_ATLAS_SECRETS_DIR) : path.join(WORKER_HOME, 'secrets');",
  'secrets path',
);
siwc = mustReplace(siwc, "const CLI = 'node integrations/openai/cli.mjs';", "const CLI = 'node rare-atlas-worker.mjs';", 'siwc CLI');

llm = stripExports(stripImports(llm));
llm = mustReplace(llm, "loadEnvFile(path.join(PROJECT_ROOT, '.env.local'));\n", '', 'env file load');
llm = mustReplace(llm, "const CLI = 'node integrations/openai/cli.mjs';\n", '', 'llm CLI');
llm = mustReplace(llm, "const isObject = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);\n", '', 'llm isObject');

const header = `#!/usr/bin/env node
/* eslint-disable -- generated file (pipeline/crowd/build_worker.mjs) */
/**
 * rare-atlas-worker.mjs: research rare diseases for the Rare Disease Atlas with YOUR OpenAI access.
 * Single file, no dependencies, Node >= 20. Run: node rare-atlas-worker.mjs --help
 *
 * What it does: claims a disease from the atlas research queue, sends the PubMed abstracts the atlas
 * fetched to your OpenAI model (your ChatGPT Plus/Pro plan via Sign in with ChatGPT, or OPENAI_API_KEY),
 * submits the extracted claims (the atlas verifies every quote), hands the disease back, repeats.
 * Talks only to the --server you give, auth.openai.com and api.openai.com. Your ChatGPT tokens stay on
 * this machine (~/.rare-atlas-worker/secrets, mode 600) and are never sent to the atlas.
 *
 * Generated by pipeline/crowd/build_worker.mjs from integrations/openai/siwc.mjs, integrations/openai/llm.mjs
 * and pipeline/crowd/worker_main.mjs. Do not edit by hand.
 */
import { createServer } from 'node:http';
import { spawn } from 'node:child_process';
import { createHash, createPublicKey, randomBytes, randomUUID, timingSafeEqual, verify as verifySignature } from 'node:crypto';
import { chmod, mkdir, open, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import readline from 'node:readline';
import { setTimeout as sleep } from 'node:timers/promises';

const WORKER_HOME = path.resolve(process.env.RARE_ATLAS_HOME || path.join(os.homedir(), '.rare-atlas-worker'));

// ===========================================================================
// Sign in with ChatGPT (copied from integrations/openai/siwc.mjs)
// ===========================================================================
`;

const glue = `
// ===========================================================================
// OpenAI Responses API client (copied from integrations/openai/llm.mjs)
// ===========================================================================
const siwcStatus = status;
`;

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, `${header}${siwc}\n${glue}${llm}\n${main}`, { mode: 0o644 });
execFileSync(process.execPath, ['--check', OUT]);
const lines = readFileSync(OUT, 'utf8').split('\n').length;
console.log(`[crowd] wrote ${path.relative(ROOT, OUT)} (${lines} lines; syntax OK)`);
