"""Therapy claims, part 2 (needles only). Evidence tuples: (ref, needle, study_type)."""
RCT = "clinical_trial"
CS = "case_series"

THERAPIES_2 = [
    {"slug": "sodium-channel-blockers", "label": "Sodium channel blocking anti-seizure medicines (class)",
     "synonyms": ["carbamazepine", "oxcarbazepine", "phenytoin", "lamotrigine", "lacosamide", "SCBs"],
     "modality": "repurposed_drug", "stage": "approved",
     "summary": "A class of established anti-seizure medicines that reduce sodium channel activity. Published "
                "responses differ by gene and by variant mechanism.",
     "node_evidence": [("PMID:41515912", "contraindicated in loss-of-function cases but beneficial in gain-of-function forms", "review")],
     "targets": [("mech:voltage-gated-sodium-channel-activity",
                  [("PMID:38148154", "phenytoin (sodium channel blocker) reduced the excitability", "functional_study")])],
     "diseases": {
         "SCN2A": {"evidence": [("PMID:28379373", "sodium channel blockers was often associated with clinically relevant seizure reduction", "cohort"),
                                ("PMID:38148154", "phenytoin (sodium channel blocker) reduced the excitability", "functional_study")],
                   "counter": [("PMID:28379373", "sodium channel blockers were rarely effective in epilepsies with later onset", "cohort")],
                   "effect_by_mechanism": {"gain-of-function": "supporting evidence", "loss-of-function": "counter-evidence"},
                   "note": "Source reports response in early-onset (gain-of-function) cases and rare effectiveness with occasional worsening in later-onset (loss-of-function) cases."},
         "SCN8A": {"evidence": [("PMID:34431999", "Gain-of-function variant carriers responded significantly better to sodium channel blockers", "cohort")],
                   "counter": [("PMID:41515912", "contraindicated in loss-of-function cases but beneficial in gain-of-function forms", "review")],
                   "effect_by_mechanism": {"gain-of-function": "supporting evidence", "loss-of-function": "counter-evidence"},
                   "note": "Source reports better response in gain-of-function carriers; a review states the class is contraindicated in loss-of-function cases."},
         "SCN1A": {"evidence": [("PMID:35696452", "gain of function variants were associated with a reduction in seizures in response to sodium channel blocker", "cohort"),
                                ("PMID:36636894", "Sodium channel blockers never worsened seizures", CS)],
                   "counter": [("PMID:9596203", "LTG induced worsening in 17 (80%) patients", CS),
                               ("PMID:36314457", "are generally considered contraindicated in Dravet syndrome", "cohort"),
                               ("PMID:41515912", "contraindicated in loss-of-function cases but beneficial in gain-of-function forms", "review"),
                               ("NCT04873869", "worsening on sodium channel blockers", RCT)],
                   "effect_by_mechanism": {"gain-of-function": "supporting evidence", "loss-of-function (Dravet)": "counter-evidence"},
                   "note": "Supporting evidence concerns rare SCN1A gain-of-function variants; the counter-evidence concerns loss-of-function Dravet syndrome."},
         "KCNQ2": {"evidence": [("PMID:42610455", "emerged as the most effective ASMs in both LOF groups", "cohort"),
                                ("PMID:25880994", "achieved seizure control within 2 weeks of carbamazepine", CS)],
                   "counter": [("PMID:42610455", "early treatment is not universally transformative", "cohort")],
                   "note": "Reported most effective in KCNQ2 loss-of-function groups, although KCNQ2 is a potassium channel."}}},
    {"slug": "kv7-openers", "label": "Kv7 potassium channel openers (ezogabine / retigabine, XEN496)", "synonyms": ["ezogabine", "retigabine", "XEN496"],
     "modality": "repurposed_drug", "stage": "clinical",
     "summary": "Drugs that open KCNQ2/KCNQ3 (Kv7) potassium channels, studied in KCNQ2 encephalopathy due to loss-of-function variants.",
     "node_evidence": [("PMID:27602407", "EZO appeared well tolerated and potentially beneficial", CS)],
     "targets": [("mech:potassium-channel-activity", [("PMID:27602407", "EZO appeared well tolerated and potentially beneficial", CS)])],
     "diseases": {
         "KCNQ2": {"evidence": [("PMID:27602407", "EZO appeared well tolerated and potentially beneficial", CS),
                                ("NCT04639310", "potential antiseizure effects of adjunctive XEN496 (ezogabine)", RCT)],
                   "counter": [("NCT04639310", "Sponsor decision; Not a safety decision", RCT),
                               ("NCT04639310", "Presence of a known gain-of-function variant in the KCNQ2 gene", RCT),
                               ("PMID:28139826", "need different targeted therapeutic approaches", CS)],
                   "effect_by_mechanism": {"loss-of-function": "supporting evidence", "gain-of-function": "excluded from the phase 3 trial"},
                   "note": "Retrospective support in loss-of-function KCNQ2; the phase 3 trial was terminated by the sponsor and excluded gain-of-function variants."}}},
    {"slug": "quinidine", "label": "Quinidine (KCNT1 channel blocker, repurposed)", "synonyms": ["quinidine"],
     "modality": "repurposed_drug", "stage": "clinical",
     "summary": "An antiarrhythmic drug and partial KCNT1 antagonist tried in KCNT1 gain-of-function epilepsies, with mixed results.",
     "node_evidence": [("PMID:25042079", "quinidine is a partial antagonist of KCNT1", "case_report")],
     "targets": [("mech:potassium-channel-activity", [("PMID:25042079", "quinidine is a partial antagonist of KCNT1", "case_report")])],
     "diseases": {
         "KCNT1": {"evidence": [("PMID:25042079", "Treatment with quinidine was correlated with a marked reduction in seizure frequency", "case_report"),
                                ("PMID:26369628", "had 80% reduction in seizure frequency", "case_report")],
                   "counter": [("PMID:29196578", "Quinidine did not show efficacy in adults and teenagers with ADNFLE", RCT),
                               ("PMID:29196578", "Dose-limiting cardiac side effects were observed", RCT),
                               ("PMID:26369628", "did not improve", "case_report")],
                   "note": "Case reports describe seizure reduction; a small randomized crossover trial in ADNFLE found no efficacy and cardiac side effects."}}},
    {"slug": "kcnt1-aso", "label": "KCNT1-targeting antisense oligonucleotide (knockdown)", "synonyms": ["Kcnt1 gapmer ASO"],
     "modality": "aso", "stage": "clinical",
     "summary": "Antisense oligonucleotides that lower KCNT1 expression; tested in mice and given investigationally to two infants.",
     "node_evidence": [("PMID:36173683", "proof of concept for ASO-based gene silencing", "animal_model")],
     "diseases": {
         "KCNT1": {"evidence": [("PMID:36173683", "proof of concept for ASO-based gene silencing", "animal_model"),
                                ("PMID:41981306", "led to a significant reduction in seizure frequency and intensity", "case_report")],
                   "counter": [("PMID:41981306", "associated with the development of ventricular enlargement or hydrocephalus", "case_report")],
                   "note": "Mouse proof of concept and two treated infants; both infants developed ventricular enlargement or hydrocephalus."}}},
    {"slug": "elsunersen", "label": "Elsunersen (PRAX-222, SCN2A-targeting antisense oligonucleotide)", "synonyms": ["PRAX-222"],
     "modality": "aso", "stage": "clinical",
     "summary": "An antisense oligonucleotide that lowers SCN2A expression, studied in early-onset gain-of-function SCN2A DEE.",
     "node_evidence": [("PMID:40263630", "a gapmer antisense oligonucleotide targeting SCN2A", "case_report")],
     "targets": [("mech:gain-of-function", [("PMID:34850743", "targeted reduction in SCN2A expression could substantially improve", "animal_model")])],
     "diseases": {
         "SCN2A": {"evidence": [("PMID:40263630", "reduction in seizure frequency corresponding to five to seven seizures per hour", "case_report"),
                                ("PMID:34850743", "reduced spontaneous seizures and significantly extended life span", "animal_model"),
                                ("NCT07019922", "Has a documented Gain of Function SCN2A variant", RCT)],
                   "note": "Single-patient expanded-access report, mouse data, and a phase 3 trial restricted to gain-of-function SCN2A variants."}}},
    {"slug": "relutrigine", "label": "Relutrigine (PRAX-562)", "synonyms": ["PRAX-562"], "modality": "small_molecule", "stage": "clinical",
     "summary": "An investigational small molecule in a trial for early-onset SCN2A and SCN8A DEE that excludes loss-of-function variants.",
     "node_evidence": [("NCT05818553", "PRAX-562 in Subjects With Developmental and Epileptic Encephalopathies", RCT)],
     "diseases": {
         "SCN2A": {"evidence": [("NCT05818553", "Has a documented variant in SCN2A with onset of seizures occurring in the first 3 months", RCT)],
                   "counter": [("NCT05818553", "functionally characterized loss-of-function (LoF) missense variant", RCT)],
                   "note": "Trial enrols early-onset SCN2A; loss-of-function variants are an exclusion criterion."},
         "SCN8A": {"evidence": [("NCT05818553", "Has a documented variant in SCN2A with onset of seizures occurring in the first 3 months", RCT)],
                   "counter": [("NCT05818553", "functionally characterized loss-of-function (LoF) missense variant", RCT)],
                   "note": "Same trial enrols SCN8A-DEE; loss-of-function variants are an exclusion criterion."}}},
    {"slug": "nbi-921352", "label": "NBI-921352 (XEN901)", "synonyms": ["XEN901"], "modality": "small_molecule", "stage": "clinical",
     "summary": "An investigational adjunctive therapy tested in SCN8A DEE; the phase 2 trial was terminated by sponsor decision.",
     "node_evidence": [("NCT04873869", "NBI-921352 as adjunctive therapy for seizures in subjects with SCN8A", RCT)],
     "diseases": {
         "SCN8A": {"evidence": [("NCT04873869", "NBI-921352 as adjunctive therapy for seizures in subjects with SCN8A", RCT)],
                   "counter": [("NCT04873869", "prematurely terminated due to sponsor decision", RCT)],
                   "note": "Phase 2 in SCN8A-DEE, terminated by sponsor decision."}}},
    {"slug": "scn8a-aso", "label": "Scn8a-lowering antisense oligonucleotide (preclinical)", "synonyms": ["Scn8a ASO"],
     "modality": "aso", "stage": "preclinical",
     "summary": "An antisense oligonucleotide that lowers Scn8a; protective in mouse models of SCN8A encephalopathy and of Dravet syndrome.",
     "node_evidence": [("PMID:31943325", "Reduction of Scn8a transcript by 25 to 50% delayed seizure onset", "animal_model")],
     "diseases": {
         "SCN8A": {"evidence": [("PMID:31943325", "Reduction of Scn8a transcript by 25 to 50% delayed seizure onset", "animal_model")],
                   "note": "Mouse data only."},
         "SCN1A": {"evidence": [("PMID:31943325", "extended survival of Dravet syndrome mice", "animal_model")],
                   "note": "Lowering a different sodium channel gene (Scn8a) extended survival in Scn1a+/- Dravet mice (mouse data only)."}}},
]
